name       : perl-extutils-install
version    : 2.14
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-Install-2.14.tar.gz : 35412305cbae979aac3b6e2c70cb301ae461979a1d848a8a043f74518eb96aea
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Install - install files from here to there
description: |
    ExtUtils::Install - install files from here to there
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
