name       : perl-extutils-install
version    : '2.22'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-Install-2.22.tar.gz : 33725bafbed3829d613e4c651c2e1ad120670c7d2ac5cf05f83757fc975d6ff2
homepage   : https://metacpan.org/pod/ExtUtils::Install
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Install - install files from here to there
description: |
    Handles the installing and uninstalling of perl modules, scripts, man pages, etc... Both install() and uninstall() are specific to the way ExtUtils::MakeMaker handles the installation and deinstallation of perl modules. They are not designed as general purpose tools.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
