name       : perl-extutils-install
version    : '2.20'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-Install-2.20.tar.gz : a4a1f1c5ab94b0a10ad81e037d5a2277fb55224760ac9013b8e196cedc829148
homepage   : https://metacpan.org/pod/ExtUtils::Install
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Install - install files from here to there
description: |
    Handles the installing and uninstalling of perl modules, scripts, man pages, etc... Both install() and uninstall() are specific to the way ExtUtils::MakeMaker handles the installation and deinstallation of perl modules. They are not designed as general purpose tools.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
